id: P007111
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG16720
  title: རྒྱུན་ཤེས་གླིང་ག
  author: ''
  volumes:
    7fd8255a333f40a8b3d40c08f87b268a:
      image_group_id: I2PD18891
      title: Volume 1 of rgyun shes gling ga
      volume_number: 1
      total_pages: 162
      base_file: v001.txt
