id: P007111
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16720
  title: རྒྱུན་ཤེས་གླིང་ག
  author: ''
  volumes:
    90ae5f62dda742e1a0cdaa4eff2fc5aa:
      image_group_id: I2PD18891
      title: ''
      volume_number: 1
      total_pages: 162
ebook_metadata:
  title: རྒྱུན་ཤེས་གླིང་ག
  author: ''
  sku: P007111
  cover: cover.jpg
  layers:
  - pagination
